// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW4OvHU_O8PG92X86qnWI63IKH3M7Onkg',
    appId: '1:211674153746:web:7e1b567579b42c1ff429cb',
    messagingSenderId: '211674153746',
    projectId: 'hospital-apps-4f3fe',
    authDomain: 'hospital-apps-4f3fe.firebaseapp.com',
    storageBucket: 'hospital-apps-4f3fe.firebasestorage.app',
    measurementId: 'G-4WJWKYFHCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM2JprJMpsaUg0R5LWp0tW-e2iO2L4liM',
    appId: '1:211674153746:android:ac0a4fd104ed1b92f429cb',
    messagingSenderId: '211674153746',
    projectId: 'hospital-apps-4f3fe',
    storageBucket: 'hospital-apps-4f3fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Libfe6U2N08P6_1aPQP1iro6oLkUOS4',
    appId: '1:211674153746:ios:0492e1e958b03b18f429cb',
    messagingSenderId: '211674153746',
    projectId: 'hospital-apps-4f3fe',
    storageBucket: 'hospital-apps-4f3fe.firebasestorage.app',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Libfe6U2N08P6_1aPQP1iro6oLkUOS4',
    appId: '1:211674153746:ios:0492e1e958b03b18f429cb',
    messagingSenderId: '211674153746',
    projectId: 'hospital-apps-4f3fe',
    storageBucket: 'hospital-apps-4f3fe.firebasestorage.app',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW4OvHU_O8PG92X86qnWI63IKH3M7Onkg',
    appId: '1:211674153746:web:098d4458db37cd94f429cb',
    messagingSenderId: '211674153746',
    projectId: 'hospital-apps-4f3fe',
    authDomain: 'hospital-apps-4f3fe.firebaseapp.com',
    storageBucket: 'hospital-apps-4f3fe.firebasestorage.app',
    measurementId: 'G-CP33M8Q9BV',
  );
}
